### ISSUE TITLE
Feature request: Add a --version|-V flag

### ISSUE THREAD

**Issue by yw5vruox7dr** [ITRS-Group/check_k8s#39]
It seems that at the moment there is no version for the script. A `--version|-V` option could catch some cases that are due to outdated script versions. Troubleshooting can also be made a bit faster this way.

**Comment by erikdsjostrom** [comment]
Makes sense, thanks for all the good ideas.

**Comment by erikdsjostrom** [comment]
This has now been implemented in #40
